Repository yawarakaijs/yawarakai, pull requests merged in 2020-06, with the labels that each got.

#22 :recycle: Refactored the code logic on handling component management
  Core/bot.js
Labels: bug, enhancement

#23 Optimization and API change adaption
  Core/Bot/telegram.js
  Core/bot.js
  Core/lang/en-US.json
  Core/lang/ja-JP.json
  Core/lang/zh-CN.json
  Core/lang/zh-HK.json
  Core/lang/zh-TW.json
  Core/storage.js
  app.js
  core.js
  package-lock.json
Labels: bug, enhancement

#24 🌐 Update 'zh-HK','zh-TW','ja-JP' Launage Files.
  Core/lang/ja-JP.json
  Core/lang/zh-HK.json
  Core/lang/zh-TW.json
Labels: enhancement, i18n

#25 Update to 1.4.3
  Core/Bot/broadcast.js
  Core/Bot/callbackquery.js
  Core/Bot/command.js
  Core/Bot/scene.js
  app.js
  package.json
Labels: enhancement

#26 ✨ Update to 1.4.3
  .gitignore
  Components/yawarakai-official/comment.js
  Components/yawarakai-official/config.json
  Components/yawarakai-official/dictionary.js
  Components/yawarakai-official/flight.js
  Components/yawarakai-official/lib/dictlib.js
  Components/yawarakai-official/musicshare.js
  Components/yawarakai-official/what2eat.js
  Components/yawarakai-official/wiki.js
  Core/Bot/admin.js
  Core/Bot/broadcast.js
  Core/Bot/callbackquery.js
  Core/Bot/command.js
  Core/Bot/diagnosticlog.js
  Core/Bot/discord.js
  Core/Bot/message.js
  Core/Bot/processor/cbqprocessor.js
  Core/Bot/processor/msgprocessor.js
  Core/Bot/processor/sceneprocessor.js
  Core/Bot/scene.js
  Core/Bot/session.js
  Core/Bot/telegram.js
  Core/bot.js
  Core/lang/en-US.json
  Core/lang/ja-JP.json
  Core/lang/zh-CN.json
  Core/lang/zh-HK.json
  Core/lang/zh-TW.json
  Core/log.js
  Core/manage/composer.js
  Core/session.js
  Core/storage.js
  README.md
  app.js
  component.js
  config.json.example
  core.js
  package.json
  yarn.lock
Labels: enhancement, i18n

#27 🚑 Fixed the bot name is not been shown correctly
  Core/Bot/command.js
  Core/Bot/processor/sceneprocessor.js
  Core/bot.js
  Core/log.js
Labels: bug

#28 🚑 Hotfix: the bot name is not been shown correctly
  Core/Bot/command.js
  Core/Bot/processor/sceneprocessor.js
  Core/bot.js
  Core/log.js
Labels: bug

#29 🚑 Fixed the component name is shown duplicately
  component.js
Labels: bug

#30 🚑 Hotfix: the component name is shown duplicately
  component.js
Labels: bug

#31 🚑 Hotfix: Broadcast functionality and MusicShare returning bug
  Core/Bot/broadcast.js
  Core/Bot/callbackquery.js
  Core/Bot/processor/sceneprocessor.js
  Core/bot.js
  README.md
Labels: bug

#33 🚑 Hotfix: broadcast and MusicShare functionality and diagnostic changes
  Core/Bot/broadcast.js
  Core/Bot/callbackquery.js
  Core/Bot/diagnosticlog.js
  Core/Bot/processor/sceneprocessor.js
  Core/bot.js
  README.md
Labels: bug, enhancement
